package view;

public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnConsultaCliente = new javax.swing.JButton();
        btnConsultaLivro = new javax.swing.JButton();
        btnCadastroLivro = new javax.swing.JButton();
        btnCadastroCliente = new javax.swing.JButton();
        btnRegistrarEmprestimo = new javax.swing.JButton();
        btnConsultarDevolucoes = new javax.swing.JButton();
        btnRegistrarDevolucao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cenaflix");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("DOCE LEITURA");

        btnConsultaCliente.setText("CONSULTA DE CLIENTES");
        btnConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaClienteActionPerformed(evt);
            }
        });

        btnConsultaLivro.setText("CONSULTA DE LIVROS");
        btnConsultaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaLivroActionPerformed(evt);
            }
        });

        btnCadastroLivro.setText("CADASTRO DE LIVRO");
        btnCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroLivroActionPerformed(evt);
            }
        });

        btnCadastroCliente.setText("CADASTRO DE CLIENTE");
        btnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroClienteActionPerformed(evt);
            }
        });

        btnRegistrarEmprestimo.setText("REGISTRAR EMPRESTIMO");
        btnRegistrarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEmprestimoActionPerformed(evt);
            }
        });

        btnConsultarDevolucoes.setText("CONSULTAR DEVOLUÇÕES");
        btnConsultarDevolucoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarDevolucoesActionPerformed(evt);
            }
        });

        btnRegistrarDevolucao.setText("REGISTRAR DEVOLUÇÃO");
        btnRegistrarDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDevolucaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConsultarDevolucoes, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnCadastroLivro)
                .addGap(18, 18, 18)
                .addComponent(btnConsultaLivro)
                .addGap(18, 18, 18)
                .addComponent(btnCadastroCliente)
                .addGap(18, 18, 18)
                .addComponent(btnConsultaCliente)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarDevolucao)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarDevolucoes)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroClienteActionPerformed
        CadastroCliente telaCadastroCliente = new CadastroCliente();
        telaCadastroCliente.setVisible(true);
    }//GEN-LAST:event_btnCadastroClienteActionPerformed

    private void btnConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaClienteActionPerformed
        ConsultaCliente telaConsultaCliente = new ConsultaCliente();
        telaConsultaCliente.setVisible(true);
    }//GEN-LAST:event_btnConsultaClienteActionPerformed

    private void btnConsultaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaLivroActionPerformed
        ConsultaLivro telaConsultaLivro = new ConsultaLivro();
        telaConsultaLivro.setVisible(true);
    }//GEN-LAST:event_btnConsultaLivroActionPerformed

    private void btnCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroLivroActionPerformed
        CadastroLivro telaCadastroLivro = new CadastroLivro();
        telaCadastroLivro.setVisible(true);
    }//GEN-LAST:event_btnCadastroLivroActionPerformed

    private void btnRegistrarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmprestimoActionPerformed
        RegistroEmprestimo telaRegistroEmprestimo = new RegistroEmprestimo();
        telaRegistroEmprestimo.setVisible(true);
    }//GEN-LAST:event_btnRegistrarEmprestimoActionPerformed

    private void btnConsultarDevolucoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarDevolucoesActionPerformed
        ConsultaDevolucao telaConsultaDevolucao = new ConsultaDevolucao();
        telaConsultaDevolucao.setVisible(true);
    }//GEN-LAST:event_btnConsultarDevolucoesActionPerformed

    private void btnRegistrarDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDevolucaoActionPerformed
        RegistroDevolucao telaRegistroDevolucao = new RegistroDevolucao();
        telaRegistroDevolucao.setVisible(true);
    }//GEN-LAST:event_btnRegistrarDevolucaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroCliente;
    private javax.swing.JButton btnCadastroLivro;
    private javax.swing.JButton btnConsultaCliente;
    private javax.swing.JButton btnConsultaLivro;
    private javax.swing.JButton btnConsultarDevolucoes;
    private javax.swing.JButton btnRegistrarDevolucao;
    private javax.swing.JButton btnRegistrarEmprestimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
